global:
  scrape_interval: 60s

scrape_configs:
  - job_name: "guest-hotelsoftware-api"
    metrics_path: /metrics
    scheme: https
    basic_auth:
      username_file: /run/secrets/prometheus_basic_auth_username
      password_file: /run/secrets/prometheus_basic_auth_password
    static_configs:
      - targets: ["api.guest-hotelsoftware.com"]
      
  - job_name: "uptime-isystems"
    metrics_path: /metrics
    scrape_interval: 60s
    scrape_timeout: 1m
    scheme: http
    static_configs:
      - targets:
        - host.docker.internal:3001
    basic_auth:
      username: ""
      password_file: /run/secrets/uptimekuma_apikey

rule_files:
  - "rule/alerts.yml"
  - "rule/recording_rule.yml"

alerting:
  alertmanagers:
  - scheme: http
    basic_auth:
      username_file: /run/secrets/prometheus_basic_auth_username
      password_file: /run/secrets/prometheus_basic_auth_password
  - static_configs:
    - targets:
       - localhost:9093


