services:
 
   tempo:
     image: grafana/tempo:latest
     user: root
     volumes:
       - ./shared/tempo:/etc
       - ./tempo-data:/var/tempo
     ports:
       - "3200:3200"
     entrypoint: sh -c "
       wget --no-check-certificate -O /etc/tempo.yml https://raw.githubusercontent.com/iSystems-apimentel/observability_OTEL/main/tempo/tempo.yml &&
       exec /tempo -config.file=/etc/tempo.yml"
 
   prometheus:
     image: prom/prometheus:latest
     user: root
     volumes:
       - ./shared/prometheus:/etc/prometheus
     ports:
       - "9090:9090"
     env_file:
       - .env
     entrypoint: sh -c "
       mkdir -p /run/secrets &&
       echo $API_USERNAME > /run/secrets/prometheus_basic_auth_username &&
       echo $API_PASSWORD > /run/secrets/prometheus_basic_auth_password &&
       wget --no-check-certificate -O /etc/prometheus/prometheus-local.yml https://raw.githubusercontent.com/iSystems-apimentel/observability_OTEL/main/prometheus/prometheus.yml &&
       exec /bin/prometheus --config.file=/etc/prometheus/prometheus-local.yml --web.enable-remote-write-receiver"
 
   loki:
     image: grafana/loki:latest
     user: root
     command:
       - "-config.file=/etc/loki/local-config.yaml"
     volumes:
       - ./shared/loki/chunks:/loki/chunks/
       - ./shared/loki/rules:/loki/rules/
     ports:
       - "3100:3100"
 
 
   alloy:
     image: grafana/alloy:latest
     command:
       - "-config.file=/etc/alloy/config.alloy"
     volumes:
       - ./shared/alloy:/etc/alloy
     ports:
       - "4317:4317"
       - "4318:4318"
     entrypoint: sh -c "
       apt-get update -y &&
       apt-get -y install wget &&
       wget --no-check-certificate -O /etc/alloy/config.alloy https://raw.githubusercontent.com/iSystems-apimentel/observability_OTEL/main/alloy/config-all-signals.alloy &&
       exec /bin/alloy run --server.http.listen-addr=0.0.0.0:12345 /etc/alloy/config.alloy"
 
   grafana:
     image: grafana/grafana:latest
     user: root
     volumes:
       - ./shared/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
       - ./shared/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
       - ./shared/grafana/dashboards:/var/lib/grafana/dashboards
     environment:
       - GF_AUTH_ANONYMOUS_ENABLED=false
       - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
       - GF_AUTH_DISABLE_LOGIN_FORM=false
       - GF_HTTP_TLS_SKIP_VERIFY=true
     ports:
       - "3000:3000"
     entrypoint: sh -c "
       mkdir -p /var/lib/grafana/dashboards &&
       wget --no-check-certificate -O /etc/grafana/provisioning/dashboards/dashboards.yml https://raw.githubusercontent.com/iSystems-apimentel/observability_OTEL/main/grafana/dashboards.yml &&
       wget --no-check-certificate -O /etc/grafana/provisioning/datasources/datasources.yml https://raw.githubusercontent.com/iSystems-apimentel/observability_OTEL/main/grafana/datasources.yml &&
       exec /run.sh"
   
volumes:
  prometheus-data:
  tempo-data:
